### ISSUE TITLE
Array

### ISSUE THREAD

**Issue by laggingreflex** [finwo/lucene-filter#37]
Great Lib. I'm new to lucene in general, so not sure if this issue is specific to this library or lucene. 

I'm trying to find if it's possible to search through data with arrays. 

E.g.:

```js
const lucene = require('lucene-filter')(require('lucene'));

const data = [
  { name: 'C-3PO'           , species: 'Droid', affiliation: ['Naboo', 'Rebels'] },
  { name: 'R2-D2'           , species: 'Droid', affiliation: ['Skywalker', 'Rebels' ] },
  { name: 'Anakin Skywalker', species: 'Human', affiliation: [] },
  { name: 'Obi-Wan Kenobi'  , species: 'Human', affiliation: [] },
  { name: 'Moon Moon'       , species: 'Wolf' , affiliation: [] },
];

console.log(data.filter(lucene('affiliation: Naboo')));
```
I expect the output:
```
[{ name: 'C-3PO'           , species: 'Droid', affiliation: ['Naboo', 'Rebels'] }]
```
But it doesn't. Am I doing it wrong or is it not possible?

**Comment by laggingreflex** [comment]
It seems it can be [easily implemented](https://github.com/laggingreflex/lucene-filter/commit/8b3999736b5fc95e9c088d4c814818d63b6a814a) (unless I'm overlooking something). I can help out with a PR (covering all filter cases).

**Comment by finwo** [comment]
The commit you've shown does handle closer to what solr does (one of the first lucene engines). Based on that, I'd gladly accept a PR for that.

Originally this functionality was overlooked, it wasn't in my use-case for the library yet.

**Comment by finwo** [comment]
Sorry for the delay, but your suggestion was finally merged in https://github.com/finwo/lucene-filter/pull/68

**Comment by laggingreflex** [comment]
Working, confirmed.
