### ISSUE TITLE
No implementation for >, >=, <, <=

### ISSUE THREAD

**Issue by paulcanning** [finwo/lucene-filter#70]
I'm not seeing any implementation for greater then, greater than or equal to, less than, or less then or equal to for numbers.

Would it be possible to add this in?

**Comment by finwo** [comment]
It should be possible, which would then be in the number filters, but I've not tested how they're exported by the query parser.

**Comment by paulcanning** [comment]
I've fixed the number range filter (see https://github.com/finwo/lucene-filter/pull/71) so I'm going to tackle these next

**Comment by finwo** [comment]
Awesome, merged and released as version 1.3.0
