### ISSUE TITLE
Filter list, comparison filter missing

### ISSUE THREAD

**Issue by paulcanning** [finwo/lucene-filter#74]
I forgot to add the new comparison filter to the list in https://github.com/finwo/lucene-filter/blob/master/src/filters/index.js

**Comment by paulcanning** [comment]
Fixed via https://github.com/finwo/lucene-filter/pull/75

**Comment by finwo** [comment]
Merged #75 and published as 1.4.0 (due to adding functionality, even though it's a bugfix / tiny change)
